server:
  port: 8761

management:
  context-path: /admin
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    

#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#  server:
#    waitTimeInMsWhenSyncEmpty: 0
#  instance:
#      metadataMap:
#        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}


#spring:
#  profiles: peer1
#eureka:
#  instance:
#    hostname: peer1
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9761/eureka/
#------      
#spring:
#  profiles: peer2
#eureka:
#  instance:
#    hostname: peer2
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/